NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 20
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 40
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 9999
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 9999
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 9999